package exchange

// The fulfilment sandbox.
//
// Measured in production: POST /v1/quote answered {"reachable":"none",
// "feasible":false} for every coordinate on earth, because no operator had
// ever registered. The MCP tools correctly tell an agent to ask that question
// first and to promise nothing when the answer is no — so the first thing this
// exchange said to every developer evaluating it was that it could not do
// anything, and they left. That is not a distribution problem. It is that
// there was a test mode for the money and none for the fulfilment.
//
// This is the missing half. A developer opts in with sandbox: true, and the
// job walks the real state machine on a short timer: taken by a simulated
// operator, evidence submitted, verified, settled, receipt issued. The board
// is the real board, the submission is a real api.Submission, acceptEvidence
// and settle are the real functions — so what somebody integrates against is
// the shape they will get in production, not a mock that drifts from it.
//
// Two things are deliberately not real, and both are said out loud everywhere
// they appear. The operator is not a person: nobody is dispatched, nobody
// travels, and the evidence is drawn by the function below rather than
// photographed. And no money moves.
//
// On money the choice was between a sandbox-only credit in its own principal
// namespace and bypassing the ledger entirely. This bypasses it. A sandbox
// credit would still write ledger rows, and those rows would then have to be
// excluded by hand from Audit, from the holdback queue, from payouts, from the
// statements and from the hourly anchoring batch — six places to get it wrong,
// each one a way for a synthetic dollar to become indistinguishable from a
// real one in the only record that is supposed to be trustworthy. A sandbox
// job writes no ledger row at all, which is the one guarantee that cannot rot:
// see the guards in checkFunded, settle and handleJobReceipt, each of which
// names this file.
//
// What survives a restart is the listing, not the run: the goroutine below
// dies with the process and a job caught mid-loop sits until it expires. That
// is acceptable for a sandbox and would not be for anything else.

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"image"
	"image/color"
	"image/jpeg"
	"log"
	"time"

	"github.com/lamdis-ai/lamdis-protocol/node/internal/api"
	"github.com/lamdis-ai/lamdis-protocol/node/internal/media"
)

// SandboxStep is how long each stage of a sandbox job takes.
//
// Seconds, because the whole point is that a developer sees the loop finish
// inside one debugging session rather than tomorrow. Slow enough that job
// status is worth polling twice, which is the thing they are integrating.
const SandboxStep = 2 * time.Second

// SandboxOperator is the principal the simulated operator claims as.
//
// Its own namespace, disjoint from every real worker id, so nothing it does
// can be confused for a person's record and no payout account can ever exist
// for it. Nothing signs in as it and no key maps to it.
const SandboxOperator = "sandbox:operator"

// SandboxSynthetic is the sentence that has to appear on every artefact a
// sandbox job produces. One constant rather than five paraphrases, so a
// receipt and a job status cannot end up disagreeing about how fake they are.
const SandboxSynthetic = "This is a SANDBOX job. No person was dispatched, " +
	"the evidence was generated by the exchange rather than photographed, " +
	"nothing was paid, and no money moved. It is not a record of work."

// sandboxStep is the timer, overridable so tests do not sleep for a minute.
func (s *Server) sandboxStep() time.Duration {
	if s.SandboxStep > 0 {
		return s.SandboxStep
	}
	return SandboxStep
}

// sandboxSeconds renders the step for the copy, so changing the constant
// changes the sentence rather than making it a lie.
func sandboxSeconds(d time.Duration) string {
	sec := int(d / time.Second)
	if sec < 1 {
		return "under a"
	}
	return fmt.Sprintf("%d", sec)
}

// startSandbox walks a sandbox job through the loop, in the background.
//
// Fire and forget: the caller is an HTTP handler that has already answered,
// and a developer polling job_status is how the progress is meant to be
// observed. Every failure is logged and abandons the run rather than retrying,
// because a stuck sandbox job costs nobody anything.
func (s *Server) startSandbox(job string) {
	go s.runSandbox(context.Background(), job)
}

func (s *Server) runSandbox(ctx context.Context, job string) {
	step := s.sandboxStep()
	wait := func() bool {
		t := time.NewTimer(step)
		defer t.Stop()
		select {
		case <-ctx.Done():
			return false
		case <-t.C:
			return true
		}
	}

	// Taken. The real Claim, so the seat, the lease and the capability all
	// exist exactly as they would for a person — which is what makes the
	// challenge code below real rather than invented.
	if !wait() {
		return
	}
	secret, l, err := s.Board.Claim(job, SandboxOperator)
	if err != nil {
		log.Printf("sandbox: %s could not be taken: %v", job, err)
		return
	}
	cap, ok := s.Caps.Lookup(secret)
	if !ok {
		log.Printf("sandbox: %s produced no capability", job)
		return
	}

	// Evidence. Drawn, not photographed — see sandboxFrame.
	if !wait() {
		return
	}
	img, err := sandboxFrame(job)
	if err != nil {
		log.Printf("sandbox: %s could not be given evidence: %v", job, err)
		return
	}
	sum := sha256.Sum256(img)
	art := api.Artifact{
		SHA256: hex.EncodeToString(sum[:]), Mime: "image/jpeg",
		Bytes: len(img), Kind: media.KindImage,
		// Where the code was found. "generated" rather than "text": no
		// describer read this, and writing the word a real reading would have
		// written is how a synthetic receipt starts looking like a real one.
		ChallengeSeen: "generated",
	}
	if err := s.storeArtifact(job, art, img); err != nil {
		log.Printf("sandbox: %s could not store its evidence: %v", job, err)
		return
	}

	sub := api.Submission{
		Job: job, Artifacts: []api.Artifact{art},
		Challenge:  api.ChallengeFor(job, cap),
		AttestedBy: "sandbox", Holder: cap.Holder, At: s.now(),
		Tier: l.Tier,
	}
	if l != nil {
		sub.LatE7, sub.LonE7, sub.RadiusM = l.LatE7, l.LonE7, l.RadiusM
	}

	// Verified and settled. acceptEvidence is the real function: it stores the
	// submission, persists it, and calls settle — which is where a real job's
	// money would move and where a sandbox job's does not.
	if !wait() {
		return
	}
	stored, err := s.acceptEvidence(sub)
	if err != nil {
		log.Printf("sandbox: %s was not accepted: %v", job, err)
		return
	}
	// DoneUnscored, not Done: a rehearsal must not build a completion record,
	// even for a principal nobody can sign in as.
	s.Board.DoneUnscored(job, SandboxOperator)
	if stored.Verified {
		s.Board.Accept(job)
	}
	log.Printf("sandbox: %s completed against a simulated operator; nothing was paid", job)
}

// sandboxVerify is what stands in for the verifier on a sandbox job.
//
// The real verifier looks for a challenge code that a blind describer read out
// of a photograph. There is no photograph and no describer here, so running it
// would be theatre that fails: the honest thing is to say that this submission
// was accepted by construction and to write that into Why, which travels all
// the way to the receipt.
func sandboxVerify(sub api.Submission, kind string) api.Submission {
	sub.Verified = true
	// An observation records what the evidence showed. A sandbox observation
	// showed nothing, so "true" here is a stated assumption rather than a
	// finding, and Why says so.
	sub.Finding = kind == api.KindObserve
	sub.Why = "accepted by the sandbox without verification. " + SandboxSynthetic
	return sub
}

// sandboxFrame draws the evidence.
//
// It has to be a real JPEG, because a developer will fetch it from
// /v1/jobs/{job}/evidence/{sha} and look at it. It must not be a photograph of
// anywhere, of anything, or of anybody: hazard stripes with the word SANDBOX
// across them, so the file says what it is without the JSON around it. The
// colour is derived from the job id, so two sandbox jobs are visibly different
// files and the reuse corpus is not handed the same image forever.
func sandboxFrame(job string) ([]byte, error) {
	const w, h = 480, 320
	sum := sha256.Sum256([]byte("lamdis-sandbox-frame:" + job))
	back := color.RGBA{R: 24, G: 28, B: 34, A: 255}
	stripe := color.RGBA{R: sum[0]/2 + 96, G: sum[1]/2 + 72, B: sum[2]/2 + 40, A: 255}

	img := image.NewRGBA(image.Rect(0, 0, w, h))
	for y := 0; y < h; y++ {
		for x := 0; x < w; x++ {
			c := back
			if ((x+y)/28)%2 == 0 {
				c = stripe
			}
			img.Set(x, y, c)
		}
	}
	drawSandboxWord(img, w, h)

	var buf sandboxBuffer
	if err := jpeg.Encode(&buf, img, &jpeg.Options{Quality: 82}); err != nil {
		return nil, fmt.Errorf("sandbox: drawing evidence: %w", err)
	}
	return buf.b, nil
}

// sandboxBuffer is the smallest io.Writer that keeps what was written. The
// evidence package has one of these and does not export it.
type sandboxBuffer struct{ b []byte }

func (w *sandboxBuffer) Write(p []byte) (int, error) {
	w.b = append(w.b, p...)
	return len(p), nil
}

// sandboxGlyphs is a 5x7 bitmap font covering exactly the seven letters of the
// only word this ever writes.
//
// Hand-rolled because the module has no font dependency and adding one to
// stamp a single word would be a strange trade. Each string is one row, '#'
// is ink.
var sandboxGlyphs = map[byte][7]string{
	'S': {".####", "#....", "#....", ".###.", "....#", "....#", "####."},
	'A': {"..#..", ".#.#.", "#...#", "#...#", "#####", "#...#", "#...#"},
	'N': {"#...#", "##..#", "##..#", "#.#.#", "#..##", "#..##", "#...#"},
	'D': {"####.", "#...#", "#...#", "#...#", "#...#", "#...#", "####."},
	'B': {"####.", "#...#", "#...#", "####.", "#...#", "#...#", "####."},
	'O': {".###.", "#...#", "#...#", "#...#", "#...#", "#...#", ".###."},
	'X': {"#...#", "#...#", ".#.#.", "..#..", ".#.#.", "#...#", "#...#"},
}

// drawSandboxWord stamps SANDBOX across the middle of the frame, in ink dark
// enough to read over either stripe.
func drawSandboxWord(img *image.RGBA, w, h int) {
	const word = "SANDBOX"
	const scale = 8
	glyphW, glyphH := 5*scale, 7*scale
	gap := scale
	total := len(word)*glyphW + (len(word)-1)*gap
	x0 := (w - total) / 2
	y0 := (h - glyphH) / 2

	// A plate behind the word, so it is legible whichever stripe it lands on.
	plate := color.RGBA{R: 12, G: 14, B: 18, A: 255}
	ink := color.RGBA{R: 244, G: 244, B: 240, A: 255}
	for y := y0 - scale*2; y < y0+glyphH+scale*2; y++ {
		for x := x0 - scale*2; x < x0+total+scale*2; x++ {
			if x >= 0 && x < w && y >= 0 && y < h {
				img.Set(x, y, plate)
			}
		}
	}
	for i := 0; i < len(word); i++ {
		rows, ok := sandboxGlyphs[word[i]]
		if !ok {
			continue
		}
		gx := x0 + i*(glyphW+gap)
		for ry, row := range rows {
			for rx := 0; rx < len(row); rx++ {
				if row[rx] != '#' {
					continue
				}
				for dy := 0; dy < scale; dy++ {
					for dx := 0; dx < scale; dx++ {
						img.Set(gx+rx*scale+dx, y0+ry*scale+dy, ink)
					}
				}
			}
		}
	}
}

// sandboxRefusal names the terms the sandbox cannot walk, rather than
// accepting them and leaving a job stuck halfway.
//
// Every one of these is refused because the simulated operator cannot honour
// it, or because honouring it would touch something real: a project envelope
// is the buyer's actual budget, a named vendor is an actual company, a bidding
// round needs an actual bidder, and a second seat would sit unfilled forever.
func sandboxRefusal(in CreateTaskRequest) string {
	switch {
	case in.Pricing == api.PriceBids:
		return "the sandbox has no bidders, so an open job would never be " +
			"awarded. Post it at a fixed fee_minor to walk the loop"
	case len(in.Stages) > 0 || in.PlanBy == api.PlanBySupplier:
		return "the sandbox walks a job in one visit and does not stage one. " +
			"Post it unstaged to see the loop, and stage it for real work"
	case in.ProjectID != "":
		return "a project envelope is a real budget, and a sandbox job must " +
			"never draw one down. Post it outside the project"
	case in.DirectTo != "":
		return "a named vendor is a real company. The sandbox will not send " +
			"one anything, real or otherwise"
	case in.Slots > 1:
		return "the sandbox fills exactly one seat, so any others would sit " +
			"unfilled. Post it with slots 1"
	}
	return ""
}
