package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	sdk "github.com/modelcontextprotocol/go-sdk/mcp"
)

// The exchange tools are how an agent reaches the physical world.
//
// Everything else an agent can do is reading. These four are the ones that
// touch reality: ask whether something is true out there, ask for something to
// be done, watch it happen, and take the receipt.
//
// The agent authenticates with a key its person issued, and every job it posts
// spends that person's balance under limits that person set. There is
// deliberately no tool for issuing a key, raising a limit, or approving a
// payout: an agent that could widen its own budget has no budget, and the one
// place a human decision is required must stay a human decision.
type Exchange struct {
	// BaseURL is the exchange this agent talks to.
	BaseURL string
	// Key is the agent credential, issued by the person it acts for.
	Key  string
	HTTP *http.Client
}

func NewExchange(baseURL, key string) *Exchange {
	return &Exchange{BaseURL: strings.TrimRight(baseURL, "/"), Key: key,
		HTTP: &http.Client{Timeout: 30 * time.Second}}
}

func (x *Exchange) call(ctx context.Context, method, path string, in any) (map[string]any, error) {
	var body *strings.Reader
	if in != nil {
		b, err := json.Marshal(in)
		if err != nil {
			return nil, err
		}
		body = strings.NewReader(string(b))
	} else {
		body = strings.NewReader("")
	}
	req, err := http.NewRequestWithContext(ctx, method, x.BaseURL+path, body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	if x.Key != "" {
		req.Header.Set("X-Lamdis-Key", x.Key)
	}
	// Software wrote this, whoever it acts for. Workers are told.
	req.Header.Set("X-Lamdis-Posted-By", "agent")
	// A job token stands in for a key on that one job, for an agent that
	// connected without one.
	if tok, _ := ctx.Value(tokenKey{}).(string); tok != "" {
		req.Header.Set("Authorization", "Bearer "+tok)
	}
	resp, err := x.HTTP.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	var out map[string]any
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return nil, fmt.Errorf("the exchange returned something unreadable")
	}
	if resp.StatusCode >= 400 {
		msg, _ := out["error"].(string)
		if msg == "" {
			msg = resp.Status
		}
		return out, fmt.Errorf("%s", msg)
	}
	return out, nil
}

// RegisterExchange adds the tools to an MCP server.
func RegisterExchange(s *sdk.Server, x *Exchange) {
	type observeArgs struct {
		Predicate  string  `json:"predicate" jsonschema:"what must be true, stated so a stranger with a camera could check it. Shown on the open board, so keep the exact address out of it unless that address is already public"`
		Where      string  `json:"where,omitempty" jsonschema:"the exact address or place to check; released only to whoever takes the job, never published"`
		Area       string  `json:"area,omitempty" jsonschema:"coarse locality shown on the open board, e.g. a neighbourhood or town; never put the exact address here"`
		Lat        float64 `json:"lat,omitempty" jsonschema:"latitude to fence the evidence to"`
		Lon        float64 `json:"lon,omitempty" jsonschema:"longitude to fence the evidence to"`
		RadiusM    int64   `json:"radius_m,omitempty" jsonschema:"how far from that point evidence may be taken"`
		FeeMinor   int64   `json:"fee_minor" jsonschema:"paid for usable evidence whichever way the answer turns out, in minor units"`
		BonusMinor int64   `json:"bonus_minor,omitempty" jsonschema:"paid additionally if the predicate holds"`
		Slots      int     `json:"slots,omitempty" jsonschema:"how many independent people should check (default 1)"`
		Sandbox    bool    `json:"sandbox,omitempty" jsonschema:"post this against the fulfilment sandbox instead of the real world. Nobody is dispatched, the evidence is generated by the exchange, nothing is paid and no money moves. The job walks the same states in seconds so you can finish an integration today. Every reply about it carries sandbox true; never tell a person a sandbox job is arranged"`
	}
	sdk.AddTool(s, &sdk.Tool{Name: "observe_world",
		Description: "Find out whether something is actually true in the physical " +
			"world, rather than what a website says about it. Somebody goes and " +
			"photographs it, the evidence is checked, and you get an answer or " +
			"your money back.\n\n" +
			"Money leaves your person's balance when you post this. If you connected " +
			"without a key, nothing leaves anywhere: the reply carries pay_at and " +
			"token. Send the person the pay link; the job goes live when their card " +
			"is authorised, and it is charged only for what is proven done. Keep " +
			"the token — it is how you follow the job. Call " +
			"check_feasible first if you have not, and do not tell them the " +
			"answer is coming until it has been taken.\n\n" +
			"Whoever goes is paid for honest evidence whichever way it turns " +
			"out, which is the reason a 'no' from here is worth as much as a " +
			"'yes'. Treat both as real findings: if it comes back no, tell your " +
			"person no. Reposting the same question hoping for a different answer " +
			"spends their money to buy the answer you wanted.\n\n" +
			"Write the predicate as something a stranger could photograph and " +
			"settle without knowing anything else about the situation.\n\n" +
			"Set sandbox true to post against the fulfilment sandbox instead of " +
			"the world: no board, no person, generated evidence, no money, and " +
			"the same states walked in seconds. Use it when check_feasible says " +
			"nothing is reachable and you want to finish the integration anyway. " +
			"Every reply about such a job carries sandbox true and says the " +
			"evidence is synthetic. Do not report one to your person as an " +
			"answer about the world, because it is not one."},
		func(ctx context.Context, req *sdk.CallToolRequest, a observeArgs) (*sdk.CallToolResult, any, error) {
			out, err := x.call(ctx, "POST", "/v1/tasks", map[string]any{
				"kind": "observe", "predicate": a.Predicate, "where": a.Where,
				"area": a.Area,
				"lat":  a.Lat, "lon": a.Lon, "radius_m": a.RadiusM,
				"fee_minor": a.FeeMinor, "bonus_minor": a.BonusMinor, "slots": a.Slots,
				"sandbox": a.Sandbox,
			})
			return jobResult(out, err)
		})

	// stageArg is one payable piece of a longer job.
	type stageArg struct {
		Name        string `json:"name" jsonschema:"what this piece is called, e.g. base course"`
		Deliverable string `json:"deliverable" jsonschema:"what would prove this piece specifically is done"`
		PayMinor    int64  `json:"pay_minor" jsonschema:"what this piece earns, in minor units"`
		Materials   bool   `json:"materials,omitempty" jsonschema:"true when this is reimbursement for supplies bought up front, paid against a receipt rather than against finished work"`
	}

	// unknownArg is something the buyer cannot pin down.
	type unknownArg struct {
		Name string `json:"name" jsonschema:"what is not known, e.g. driveway width"`
		Note string `json:"note,omitempty" jsonschema:"whatever your human can say about it, in their words"`
		Unit string `json:"unit,omitempty" jsonschema:"feet, square feet, hours"`
	}

	type doArgs struct {
		Predicate             string     `json:"predicate" jsonschema:"what should be true once the job is done. Shown on the open board, so keep the exact address out of it"`
		Instructions          string     `json:"instructions" jsonschema:"what the person should actually do"`
		Deliverable           string     `json:"deliverable,omitempty" jsonschema:"what proof to bring back, e.g. a photo of the parcel at the door with the house number visible"`
		Where                 string     `json:"where,omitempty" jsonschema:"the exact address; released only to whoever takes the job, never published"`
		Area                  string     `json:"area,omitempty" jsonschema:"coarse locality shown on the open board, e.g. a neighbourhood or town; never put the exact address here"`
		Lat                   float64    `json:"lat,omitempty"`
		Lon                   float64    `json:"lon,omitempty"`
		RadiusM               int64      `json:"radius_m,omitempty" jsonschema:"how far from that point the evidence may be taken"`
		FeeMinor              int64      `json:"fee_minor" jsonschema:"paid on completion, in minor units"`
		AttemptMinor          int64      `json:"attempt_minor,omitempty" jsonschema:"paid for a documented failed attempt, e.g. the shop was shut"`
		ExpenseCapMinor       int64      `json:"expense_cap_minor,omitempty" jsonschema:"how much they may lay out and reclaim against a receipt"`
		Skills                []string   `json:"skills,omitempty" jsonschema:"qualifications required, e.g. hvac, electrical, plumbing, refrigerant, locksmith, drone, cdl, notary, ladder, vehicle, lifting, cleaning, assembly, photography"`
		ProjectID             string     `json:"project_id,omitempty" jsonschema:"the budget envelope this job draws on, from open_project"`
		DirectTo              string     `json:"direct_to,omitempty" jsonschema:"send this to one of your approved vendors instead of the open board. No auction, no strangers, invisible to everybody else"`
		SiteID                string     `json:"site_id,omitempty" jsonschema:"a location from your site list, instead of typing an address"`
		Reference             string     `json:"reference,omitempty" jsonschema:"your purchase order, cost centre or work order. Carried to the receipt untouched"`
		RequireInsuredToMinor int64      `json:"require_insured_to_minor,omitempty" jsonschema:"refuse anybody whose verified public liability cover is below this"`
		WorkHours             int        `json:"work_hours,omitempty" jsonschema:"how long the work takes. Set this for anything longer than an errand, or the job is treated as abandoned partway through"`
		Stages                []stageArg `json:"stages,omitempty" jsonschema:"cut a long job into pieces that are each evidenced and paid as they are finished. Their pay must add up to fee_minor"`
		// Multi-part work. A scope with a real order between its pieces was
		// not expressible: an agent could post three jobs at one address and
		// nothing recorded that they were one job, or which had to come first.
		DependsOn []string     `json:"depends_on,omitempty" jsonschema:"job ids in the same project that must be finished and accepted before this one may be started. Use this wherever the order is real — a slab cures before anything drives on it — because otherwise two crews book the same ground for the same morning"`
		BidsAsOne bool         `json:"bids_as_one,omitempty" jsonschema:"accept a single offer covering every job in this project, priced per job and awarded together or not at all. Set this when the jobs share a site: arriving once is most of the cost of a small job, and a supplier who cannot bundle prices one mobilisation per job or loses"`
		SiteMark  string       `json:"site_mark,omitempty" jsonschema:"something visible at this property and nowhere else, which must be legible in one photograph — usually the house number. This is what separates a photo of YOUR cut lawn from a photo of A cut lawn: the code proves when it was taken, the location metadata is editable by whoever made the file, and neither says whose lawn it is. Inferred from the address when you leave it out. Set it explicitly when the number is not visible from where the work happens, and name what is instead"`
		Brief     string       `json:"brief,omitempty" jsonschema:"anything else about this job, in your own words, carried to whoever does it exactly as written and never interpreted. Put here whatever matters that no other field fits — the slope of the ground, when the owner is away, what the neighbour agreed. This is how you tell their agent what you know"`
		Access    string       `json:"access,omitempty" jsonschema:"how to get in: gate code, where the key is, alarm sequence. Released only to whoever takes the job. Never put this in instructions or brief — those are published on the open board and a job containing entry details is refused"`
		Unknowns  []unknownArg `json:"unknowns,omitempty" jsonschema:"what your human cannot specify — how wide they want the driveway, the footprint of the barn. Say so rather than guessing: a bid then has to state what it priced on and whether that price holds, and that assumption is what the finished work is judged against. Guessing instead produces a number that means nothing and an argument on site"`
		PlanBy    string       `json:"plan_by,omitempty" jsonschema:"who decides how this job breaks into stages: \"buyer\" (default, you supply stages) or \"supplier\" (the winning bidder proposes the breakdown and you accept it). Use supplier for trade work you do not know how to decompose — a homeowner does not know what a binder course is, and guessing produces a schedule the crew is then judged against"`
		Sandbox   bool         `json:"sandbox,omitempty" jsonschema:"post this against the fulfilment sandbox instead of the real world. Nobody is dispatched, the evidence is generated by the exchange, nothing is paid and no money moves. The job walks the same states in seconds so you can finish an integration today. Every reply about it carries sandbox true; never tell a person a sandbox job is arranged"`
	}
	sdk.AddTool(s, &sdk.Tool{Name: "do_in_world",
		Description: "Have something in the physical world made true — a sign hung, a " +
			"parcel collected and delivered, a filter swapped, a slab poured — by " +
			"whoever can do it: a person, a crew, a contractor, a drone, a " +
			"machine. Comes back with proof it happened.\n\n" +
			"Money leaves your person's balance when you post this. If you connected " +
			"without a key, nothing leaves anywhere: the reply carries pay_at and " +
			"token. Send the person the pay link; the job goes live when their card " +
			"is authorised, and it is charged only for what is proven done. Keep " +
			"the token — it is how you follow the job. Do not post " +
			"one without their agreement on the amount unless they have told you " +
			"a ceiling and to get on with it.\n\n" +
			"Call check_feasible first if you have not already. Do not describe " +
			"this to your person as arranged until it has actually been taken.\n\n" +
			"Write the deliverable as the thing you would need to see to believe " +
			"it — that sentence is what the evidence is judged against, and a " +
			"vague one means somebody argues about it later. Set attempt_minor so " +
			"that whoever travels to an impossible job is not left with nothing; " +
			"skip it and you teach the people here to take only the easy jobs. " +
			"Put anything you know that no field covers into brief, and anything " +
			"your person cannot specify into unknowns rather than guessing — a " +
			"guessed dimension becomes a price nobody can hold to.\n\n" +
			"Set sandbox true to post against the fulfilment sandbox instead of " +
			"the world: no board, no crew, generated evidence, no money, and the " +
			"same states walked in seconds. Use it when check_feasible says " +
			"nothing is reachable and you want to finish the integration anyway. " +
			"Every reply about such a job carries sandbox true and its receipt " +
			"says in words that the evidence is synthetic and nothing was paid. " +
			"Never tell a person a sandbox job has been arranged: nobody is " +
			"going anywhere."},
		func(ctx context.Context, req *sdk.CallToolRequest, a doArgs) (*sdk.CallToolResult, any, error) {
			out, err := x.call(ctx, "POST", "/v1/tasks", map[string]any{
				"kind": "do", "predicate": a.Predicate, "instructions": a.Instructions,
				"deliverable": a.Deliverable, "where": a.Where, "area": a.Area,
				"lat": a.Lat, "lon": a.Lon, "radius_m": a.RadiusM,
				"fee_minor": a.FeeMinor, "attempt_minor": a.AttemptMinor,
				"expense_cap_minor": a.ExpenseCapMinor, "skills": a.Skills,
				"work_hours": a.WorkHours, "stages": a.Stages,
				"project_id": a.ProjectID, "direct_to": a.DirectTo,
				"site_id": a.SiteID, "reference": a.Reference,
				"require_insured_to_minor": a.RequireInsuredToMinor,
				"depends_on":               a.DependsOn, "bids_as_one": a.BidsAsOne,
				"plan_by": a.PlanBy, "sandbox": a.Sandbox,
			})
			return jobResult(out, err)
		})

	type jobArgs struct {
		Job   string `json:"job" jsonschema:"the job id returned when it was posted"`
		Token string `json:"token,omitempty" jsonschema:"the token returned when the job was posted without an account; not needed when connected with a key"`
	}
	sdk.AddTool(s, &sdk.Tool{Name: "job_status",
		Description: "Where a job has got to: whether anybody has taken it, what they " +
			"submitted, whether it passed checking, and what was paid. A reply " +
			"carrying sandbox true is a simulated run: nobody went anywhere and " +
			"nothing was paid, whatever the states say."},
		func(ctx context.Context, req *sdk.CallToolRequest, a jobArgs) (*sdk.CallToolResult, any, error) {
			ctx = withToken(ctx, a.Token)
			out, err := x.call(ctx, "GET", "/v1/jobs/"+a.Job, nil)
			return jobResult(out, err)
		})

	sdk.AddTool(s, &sdk.Tool{Name: "job_receipt",
		Description: "The signed receipt for a finished job. It states what was asked, " +
			"what evidence arrived, what was concluded and what moved, and can be verified " +
			"by anyone without trusting the exchange. A sandbox job's receipt says " +
			"so in words, reports nothing paid, and is not anchored — it is not " +
			"evidence of anything and must never be shown as though it were."},
		func(ctx context.Context, req *sdk.CallToolRequest, a jobArgs) (*sdk.CallToolResult, any, error) {
			ctx = withToken(ctx, a.Token)
			out, err := x.call(ctx, "GET", "/v1/jobs/"+a.Job+"/receipt", nil)
			return jobResult(out, err)
		})

	sdk.AddTool(s, &sdk.Tool{Name: "job_evidence",
		Description: "The actual files somebody brought back for a job — photographs, " +
			"video, transcripts — with where each one says it was taken and whether the " +
			"challenge code was found in it. Use this when the verdict alone is not " +
			"enough and you want to look at what was bought, or show it to the person " +
			"you are acting for. Each file comes with a url you can fetch."},
		func(ctx context.Context, req *sdk.CallToolRequest, a jobArgs) (*sdk.CallToolResult, any, error) {
			ctx = withToken(ctx, a.Token)
			out, err := x.call(ctx, "GET", "/v1/jobs/"+a.Job+"/evidence", nil)
			return jobResult(out, err)
		})

	// The read primitives an orchestrator needs before any write.
	type quoteArgs struct {
		Kind         string   `json:"kind,omitempty" jsonschema:"observe or do (default do)"`
		Predicate    string   `json:"predicate,omitempty" jsonschema:"what you are thinking of asking for"`
		Detail       string   `json:"detail,omitempty" jsonschema:"the scope, as far as you know it"`
		Instructions string   `json:"instructions,omitempty"`
		Skills       []string `json:"skills,omitempty" jsonschema:"qualifications the work would need"`
		Lat          float64  `json:"lat,omitempty"`
		Lon          float64  `json:"lon,omitempty"`
		Slots        int      `json:"slots,omitempty"`
		Sandbox      bool     `json:"sandbox,omitempty" jsonschema:"ask the fulfilment sandbox instead of the world. Always feasible there, because supply is a simulated operator; it says nothing about whether the work can be done at this address"`
	}
	sdk.AddTool(s, &sdk.Tool{Name: "check_feasible",
		Description: "Call this BEFORE you tell your person that something can be " +
			"done in the physical world. It costs nothing and holds nothing.\n\n" +
			"If it comes back saying no supply is reachable, say so plainly and " +
			"do not offer to arrange it. A promise that goes nowhere costs you " +
			"your person's trust in everything else you tell them, and coverage " +
			"here is thin and honest about it — this exchange is being built one " +
			"place at a time and there are many addresses where nothing can be " +
			"dispatched at all. Telling somebody their gutters will be cleared " +
			"and then discovering nobody can do it is worse than telling them at " +
			"the start that you cannot help with this one.\n\n" +
			"An infeasible answer is not a dead end for you, only for that job. " +
			"Two things come back with it. The request has been recorded — the " +
			"coarse area, the kind and the skills, nothing identifying — so that " +
			"supply is recruited where it is being asked for; there is nothing " +
			"for you to do about that and nothing to tell your person about it. " +
			"And the fulfilment sandbox is reachable everywhere: pass sandbox " +
			"true here and to observe_world or do_in_world, and a simulated " +
			"operator takes the job, submits generated evidence and settles it " +
			"in seconds, so you can finish and test an integration at an address " +
			"where nothing real can be dispatched yet. Use it for building. " +
			"Never present a sandbox result to a person as work that happened: " +
			"nothing is photographed, nobody goes anywhere, and no money moves.\n\n" +
			"It answers how much supply is reachable for that place and those " +
			"qualifications, whether the job would be refused outright, and what " +
			"work of this shape has actually been paid here once enough of it " +
			"has.\n\n" +
			"It does not tell you what the work costs, and you should not guess " +
			"either. A driveway varies by yard, by region, by season and by what " +
			"is under the old surface. Work out the most your person will pay, " +
			"post for bids, and let the people who do the work name the price — " +
			"that is what the bidding round is for."},
		func(ctx context.Context, req *sdk.CallToolRequest, a quoteArgs) (*sdk.CallToolResult, any, error) {
			out, err := x.call(ctx, "POST", "/v1/quote", map[string]any{
				"kind": a.Kind, "predicate": a.Predicate,
				"detail": a.Detail, "instructions": a.Instructions,
				"skills": a.Skills, "lat": a.Lat, "lon": a.Lon, "slots": a.Slots,
				"sandbox": a.Sandbox,
			})
			return jobResult(out, err)
		})

	type projectArgs struct {
		Title       string `json:"title" jsonschema:"what the person actually asked for, in their words"`
		BudgetMinor int64  `json:"budget_minor" jsonschema:"the ceiling for everything under this plan, in minor units"`
	}
	sdk.AddTool(s, &sdk.Tool{Name: "open_project",
		Description: "Start a budget envelope several jobs share. Use this when " +
			"one request turns into more than one job — a survey and then the " +
			"work it informs, or stages bought separately. Jobs attached to it " +
			"draw the budget down, and a job that would exceed it is refused " +
			"with the amount remaining rather than failing as an escrow error " +
			"part-way through your plan."},
		func(ctx context.Context, req *sdk.CallToolRequest, a projectArgs) (*sdk.CallToolResult, any, error) {
			out, err := x.call(ctx, "POST", "/v1/projects", map[string]any{
				"title": a.Title, "budget_minor": a.BudgetMinor,
			})
			return jobResult(out, err)
		})

	type projectRef struct {
		Project string `json:"project" jsonschema:"the project id"`
	}
	sdk.AddTool(s, &sdk.Tool{Name: "project_status",
		Description: "What a plan has cost so far and what is left: every job " +
			"under it, what is committed, what is spent, what came back, and " +
			"the remaining budget. The question to ask before deciding what to " +
			"do next."},
		func(ctx context.Context, req *sdk.CallToolRequest, a projectRef) (*sdk.CallToolResult, any, error) {
			out, err := x.call(ctx, "GET", "/v1/projects/"+a.Project, nil)
			return jobResult(out, err)
		})

	type cancelArgs struct {
		Job    string `json:"job"`
		Reason string `json:"reason,omitempty" jsonschema:"why the plan changed"`
	}
	sdk.AddTool(s, &sdk.Tool{Name: "cancel_job",
		Description: "Withdraw a job nobody has taken yet and release its " +
			"escrow. Use this when what you learned changes the plan — a survey " +
			"that makes later work pointless, a quote that comes back too high. " +
			"Refused once somebody is holding the job or has done it: cancelling " +
			"out from under a person standing at the address is not something " +
			"this exchange does."},
		func(ctx context.Context, req *sdk.CallToolRequest, a cancelArgs) (*sdk.CallToolResult, any, error) {
			out, err := x.call(ctx, "POST", "/v1/jobs/"+a.Job+"/cancel",
				map[string]any{"reason": a.Reason})
			return jobResult(out, err)
		})

	type sweepArgs struct {
		Predicate    string   `json:"predicate" jsonschema:"what should be true at each location once done"`
		Instructions string   `json:"instructions,omitempty"`
		Deliverable  string   `json:"deliverable,omitempty"`
		Sites        []string `json:"sites" jsonschema:"site ids from your site list"`
		Sweep        string   `json:"sweep,omitempty" jsonschema:"what to call this round of work"`
		FeeMinor     int64    `json:"fee_minor" jsonschema:"paid per location"`
		DirectTo     string   `json:"direct_to,omitempty" jsonschema:"send it all to one approved vendor instead of the open board"`
		Reference    string   `json:"reference,omitempty" jsonschema:"your purchase order or cost centre, carried to every receipt"`
		Skills       []string `json:"skills,omitempty"`
		Tier         string   `json:"tier,omitempty"`
		WorkHours    int      `json:"work_hours,omitempty"`
	}
	sdk.AddTool(s, &sdk.Tool{Name: "sweep_sites",
		Description: "Describe work once and post it at many of your locations. " +
			"Each site becomes its own job, evidenced and paid separately, all " +
			"under one budget envelope you can watch with project_status. Use " +
			"this for anything that is 'the same thing at every store' — a " +
			"monthly compliance photo, a seasonal check, a fixture audit. " +
			"Addresses and access notes come from your site list rather than " +
			"being retyped, and your reference is carried to every receipt."},
		func(ctx context.Context, req *sdk.CallToolRequest, a sweepArgs) (*sdk.CallToolResult, any, error) {
			out, err := x.call(ctx, "POST", "/v1/tasks/sweep", map[string]any{
				"kind": "observe", "predicate": a.Predicate,
				"instructions": a.Instructions, "deliverable": a.Deliverable,
				"sites": a.Sites, "sweep": a.Sweep,
				"fee_minor": a.FeeMinor, "direct_to": a.DirectTo,
				"reference": a.Reference, "skills": a.Skills,
				"tier": a.Tier, "work_hours": a.WorkHours,
			})
			return jobResult(out, err)
		})

	sdk.AddTool(s, &sdk.Tool{Name: "list_vendors",
		Description: "The suppliers this account has approved, with any rates " +
			"agreed with them. Work directed to one of these skips the open " +
			"board and runs no auction, because the price was settled elsewhere."},
		func(ctx context.Context, req *sdk.CallToolRequest, _ struct{}) (*sdk.CallToolResult, any, error) {
			out, err := x.call(ctx, "GET", "/v1/vendors", nil)
			return jobResult(out, err)
		})

	sdk.AddTool(s, &sdk.Tool{Name: "list_sites",
		Description: "This account's locations, with the ids sweep_sites and " +
			"do_in_world take. Using a site id instead of typing an address " +
			"also carries that location's access notes to whoever takes the job."},
		func(ctx context.Context, req *sdk.CallToolRequest, _ struct{}) (*sdk.CallToolResult, any, error) {
			out, err := x.call(ctx, "GET", "/v1/sites", nil)
			return jobResult(out, err)
		})

	type openArgs struct {
		Predicate    string   `json:"predicate" jsonschema:"what should be true once the job is done. Shown on the open board, so keep the exact address out of it"`
		Instructions string   `json:"instructions" jsonschema:"what the person should actually do"`
		Where        string   `json:"where,omitempty" jsonschema:"the exact address; released only to whoever takes the job, never published"`
		Area         string   `json:"area,omitempty" jsonschema:"coarse locality shown on the open board, e.g. a neighbourhood or town; never put the exact address here"`
		Lat          float64  `json:"lat,omitempty"`
		Lon          float64  `json:"lon,omitempty"`
		RadiusM      int64    `json:"radius_m,omitempty"`
		MaxBidMinor  int64    `json:"max_bid_minor" jsonschema:"the most you will pay, in minor units; this is what gets held"`
		BidsCloseIn  int64    `json:"bids_close_in_hours,omitempty" jsonschema:"how long to collect offers (default 24)"`
		Deliverable  string   `json:"deliverable,omitempty" jsonschema:"what proof to bring back"`
		Skills       []string `json:"skills,omitempty" jsonschema:"qualifications required, e.g. hvac, electrical, plumbing, refrigerant, locksmith, drone, cdl, notary, ladder, vehicle, lifting, cleaning, assembly, photography"`
	}
	sdk.AddTool(s, &sdk.Tool{Name: "request_quotes",
		Description: "Post a job you do not know the price of and collect offers. Use this " +
			"when the cost depends on the specifics — mowing a lawn, clearing a gutter, a " +
			"repair — rather than guessing a figure that either overpays or sits unclaimed. " +
			"max_bid_minor is the ceiling you are willing to pay. It is NOT held: " +
			"asking a price does not cost you the maximum, so you can price " +
			"several approaches to the same problem in parallel. It is reserved " +
			"against your balance, so you cannot solicit more in quotes than you " +
			"could honour, and escrow happens when you accept a bid."},
		func(ctx context.Context, req *sdk.CallToolRequest, a openArgs) (*sdk.CallToolResult, any, error) {
			hours := a.BidsCloseIn
			if hours == 0 {
				hours = 24
			}
			out, err := x.call(ctx, "POST", "/v1/tasks", map[string]any{
				"kind": "do", "predicate": a.Predicate, "instructions": a.Instructions,
				"deliverable": a.Deliverable, "where": a.Where, "area": a.Area,
				"lat": a.Lat, "lon": a.Lon, "radius_m": a.RadiusM,
				"pricing": "bids", "max_bid_minor": a.MaxBidMinor,
				"bids_close_in_hours": hours, "fee_minor": a.MaxBidMinor,
				"skills": a.Skills,
			})
			return jobResult(out, err)
		})

	sdk.AddTool(s, &sdk.Tool{Name: "list_bids",
		Description: "The offers on an open job: what each person would charge, when they " +
			"could do it, and what they said about how. Show these to your human rather " +
			"than picking on price alone."},
		func(ctx context.Context, req *sdk.CallToolRequest, a jobArgs) (*sdk.CallToolResult, any, error) {
			ctx = withToken(ctx, a.Token)
			out, err := x.call(ctx, "GET", "/v1/jobs/"+a.Job+"/bids", nil)
			return jobResult(out, err)
		})

	type acceptArgs struct {
		Job string `json:"job"`
		Bid string `json:"bid" jsonschema:"the bid id from list_bids"`
	}
	sdk.AddTool(s, &sdk.Tool{Name: "accept_bid",
		Description: "Accept one offer. The amount becomes the price and the work begins. " +
			"Check with your human first unless they told you a ceiling and to just get on " +
			"with it."},
		func(ctx context.Context, req *sdk.CallToolRequest, a acceptArgs) (*sdk.CallToolResult, any, error) {
			out, err := x.call(ctx, "POST", "/v1/jobs/"+a.Job+"/award",
				map[string]any{"bid": a.Bid})
			return jobResult(out, err)
		})

	// Offers covering a whole project, and the plan the winner proposes.
	//
	// Without these an agent could post a scope a supplier can bundle and then
	// had no way to read the bundle or accept it — the buyer's half of the
	// feature was unreachable from the surface the buyer's agent uses.
	type projectRefArgs struct {
		Project string `json:"project" jsonschema:"the project id from open_project"`
	}
	sdk.AddTool(s, &sdk.Tool{Name: "list_project_bids",
		Description: "Offers covering a whole project at once: what one supplier would " +
			"charge for every piece, priced per piece, with how they would sequence it. " +
			"A bundle is usually cheaper than the same jobs bid separately, because " +
			"arriving once is most of the cost of a small job."},
		func(ctx context.Context, req *sdk.CallToolRequest, a projectRefArgs) (*sdk.CallToolResult, any, error) {
			out, err := x.call(ctx, "GET", "/v1/projects/"+a.Project+"/bids", nil)
			return jobResult(out, err)
		})

	type acceptScopeArgs struct {
		Project string `json:"project"`
		Bid     string `json:"bid" jsonschema:"the offer id from list_project_bids"`
	}
	sdk.AddTool(s, &sdk.Tool{Name: "accept_project_bid",
		Description: "Accept one offer covering several jobs. Every piece is awarded to " +
			"that supplier and escrowed at its line amount, together or not at all. " +
			"Check with your human first unless they set a ceiling and told you to get on " +
			"with it — this commits the whole scope at once."},
		func(ctx context.Context, req *sdk.CallToolRequest, a acceptScopeArgs) (*sdk.CallToolResult, any, error) {
			out, err := x.call(ctx, "POST", "/v1/projects/"+a.Project+"/award",
				map[string]any{"bid": a.Bid})
			return jobResult(out, err)
		})

	type planArgs struct {
		Job string `json:"job"`
	}
	sdk.AddTool(s, &sdk.Tool{Name: "read_stage_plan",
		Description: "The breakdown a supplier proposed for a job you posted with " +
			"plan_by \"supplier\": the stages, what proves each, and what each is worth. " +
			"Nothing starts until you accept it."},
		func(ctx context.Context, req *sdk.CallToolRequest, a planArgs) (*sdk.CallToolResult, any, error) {
			out, err := x.call(ctx, "GET", "/v1/jobs/"+a.Job+"/plan", nil)
			return jobResult(out, err)
		})

	type decidePlanArgs struct {
		Job    string `json:"job"`
		Accept bool   `json:"accept" jsonschema:"true to agree to the breakdown, false to send it back"`
		Why    string `json:"why,omitempty" jsonschema:"required when sending it back: what you would accept instead"`
	}
	sdk.AddTool(s, &sdk.Tool{Name: "decide_stage_plan",
		Description: "Accept a supplier's stage breakdown, or send it back with a reason. " +
			"Accepting is what lets the crew start, and each stage is then paid as its own " +
			"evidence is accepted rather than everything at the end. The total cannot " +
			"change: it was settled when you accepted their bid."},
		func(ctx context.Context, req *sdk.CallToolRequest, a decidePlanArgs) (*sdk.CallToolResult, any, error) {
			out, err := x.call(ctx, "POST", "/v1/jobs/"+a.Job+"/plan",
				map[string]any{"accept": a.Accept, "why": a.Why})
			return jobResult(out, err)
		})

	type findOutArgs struct {
		Question     string `json:"question" jsonschema:"what you need found out, e.g. quotes for a new water heater"`
		Where        string `json:"where,omitempty" jsonschema:"the address it concerns"`
		Instructions string `json:"instructions" jsonschema:"how to go about it, e.g. call three local installers"`
		Rows         int    `json:"rows,omitempty" jsonschema:"how many results to collect, e.g. 3 quotes"`
		FeeMinor     int64  `json:"fee_minor" jsonschema:"what this is worth to you, in minor units"`
	}
	sdk.AddTool(s, &sdk.Tool{Name: "find_out",
		Description: "Pay somebody to go and find something out, and get a structured answer " +
			"back rather than a photograph. Use for quotes, availability, opening hours, " +
			"stock — anything where the deliverable is information. Each result comes back " +
			"as provider, price, availability and notes, so you can act on it without parsing prose."},
		func(ctx context.Context, req *sdk.CallToolRequest, a findOutArgs) (*sdk.CallToolResult, any, error) {
			rows := a.Rows
			if rows == 0 {
				rows = 3
			}
			// An observation, not a do-job: the worker finds out what is
			// already true and writes it down. Posted as "do" it could only
			// settle on an adjudicated photograph of the work, which a table
			// of quotes is not.
			out, err := x.call(ctx, "POST", "/v1/tasks", map[string]any{
				"kind": "observe", "predicate": a.Question, "instructions": a.Instructions,
				"where": a.Where, "fee_minor": a.FeeMinor,
				"deliverable": fmt.Sprintf("%d results", rows),
				"report": []map[string]any{
					{"name": "provider", "label": "Who", "kind": "text", "required": true, "repeats": true},
					{"name": "price", "label": "Quoted price", "kind": "money", "repeats": true},
					{"name": "available", "label": "Earliest date", "kind": "date", "repeats": true},
					{"name": "phone", "label": "Contact", "kind": "phone", "repeats": true},
					{"name": "notes", "label": "Anything else", "kind": "text", "repeats": true},
				},
			})
			return jobResult(out, err)
		})

	sdk.AddTool(s, &sdk.Tool{Name: "exchange_balance",
		Description: "What this agent's account holds, what is committed to open jobs, " +
			"and what remains spendable under the limits its person set."},
		func(ctx context.Context, req *sdk.CallToolRequest, _ struct{}) (*sdk.CallToolResult, any, error) {
			out, err := x.call(ctx, "GET", "/v1/agent/balance", nil)
			return jobResult(out, err)
		})
}

func jobResult(out map[string]any, err error) (*sdk.CallToolResult, any, error) {
	if err != nil {
		return &sdk.CallToolResult{
			IsError: true,
			Content: []sdk.Content{&sdk.TextContent{Text: err.Error()}},
		}, nil, nil
	}
	b, _ := json.MarshalIndent(out, "", "  ")
	return &sdk.CallToolResult{
		Content: []sdk.Content{&sdk.TextContent{Text: string(b)}},
	}, out, nil
}

// tokenKey carries a job token through a tool call to the request it makes.
type tokenKey struct{}

func withToken(ctx context.Context, tok string) context.Context {
	if tok == "" {
		return ctx
	}
	return context.WithValue(ctx, tokenKey{}, tok)
}

// GuestTools is what an agent gets with no credential at all.
//
// Reads, the feasibility check, and the two ways of posting a job — which come
// back with a pay link and a token instead of drawing on a balance — plus the
// tools that follow a job by that token. Everything that presumes an account
// (projects, vendors, sites, balances, quotes over a reservation) is left off
// rather than left to fail.
var GuestTools = []string{
	"check_feasible", "observe_world", "do_in_world", "find_out",
	"job_status", "job_receipt", "job_evidence", "list_bids",
}

// RegisterGuest registers the buyer tools an anonymous caller may use.
func RegisterGuest(s *sdk.Server, x *Exchange) {
	RegisterExchange(s, x)
	keep := map[string]bool{}
	for _, n := range GuestTools {
		keep[n] = true
	}
	var drop []string
	for _, n := range ExchangeToolNames {
		if !keep[n] {
			drop = append(drop, n)
		}
	}
	s.RemoveTools(drop...)
}

// ExchangeToolNames lists every buyer tool RegisterExchange adds, in order.
var ExchangeToolNames = []string{
	"observe_world", "do_in_world", "job_status", "job_receipt", "job_evidence",
	"check_feasible", "open_project", "project_status", "cancel_job", "sweep_sites",
	"list_vendors", "list_sites", "request_quotes", "list_bids", "accept_bid",
	"list_project_bids", "accept_project_bid", "read_stage_plan", "decide_stage_plan",
	"find_out", "exchange_balance",
}
